services:
  postgres:
    container_name: postgres_pet_family
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pet_family_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    container_name: seq_pet_family
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
volumes:
  postges-data:

